# Generated by Django 2.2.14 on 2021-01-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('petite_description', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('plus_information', models.CharField(max_length=500)),
                ('categorie', models.CharField(max_length=50)),
                ('prix', models.IntegerField()),
                ('stock', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('picture_1', models.URLField()),
                ('picture_2', models.URLField()),
                ('picture_3', models.URLField()),
                ('picture_4', models.URLField()),
                ('picture_5', models.URLField()),
                ('picture_6', models.URLField()),
            ],
        ),
    ]
