# Generated by Django 2.2.14 on 2021-01-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_contact_demande_reparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='address',
            field=models.CharField(default='address', max_length=100),
        ),
        migrations.AddField(
            model_name='reparation',
            name='prix',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
