# Generated by Django 2.2.14 on 2021-01-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210106_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='etat',
            field=models.CharField(default='neuf', max_length=50),
        ),
    ]
